on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_INSTALL_FROM_API: 1
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae --testing-formulae oxigraph
      - name: Upload bottles as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'
