name: test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew tap oxigraph/oxigraph
      - run: brew install --verbose oxigraph
      - run: brew test oxigraph
      - run: brew audit --new oxigraph --tap oxigraph/oxigraph
